---
abstract: 'DBRs Dist::Zilla PluginBundle'
author:
  - 'Daniel B. <dbr@cpan.org>'
build_requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.006
  Test::More: 0.94
  Test::UseAllModules: 0
  perl: 5.004
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-DBR
provides:
  Dist::Zilla::PluginBundle::Author::DBR:
    file: lib/Dist/Zilla/PluginBundle/Author/DBR.pm
    version: v1.2.0
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoMetaResources: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0
  Dist::Zilla::Plugin::CheckVersionIncrement: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides::Class: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReportPhase: 0
  Dist::Zilla::Plugin::ReportVersions: 0
  Dist::Zilla::Plugin::Run::Release: 0
  Dist::Zilla::Plugin::RunExtraTests: 0
  Dist::Zilla::Plugin::SchwartzRatio: 0
  Dist::Zilla::Plugin::ShareDir::Tarball: 0
  Dist::Zilla::Plugin::SpellingCommonMistakesTests: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0
  Dist::Zilla::Plugin::Test::ChangesHasContent: 0
  Dist::Zilla::Plugin::Test::CheckDeps: 0
  Dist::Zilla::Plugin::Test::CheckManifest: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::Legal: 0
  Dist::Zilla::Plugin::Test::MinimumVersion: 0
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Plugin::Test::Portability: 0
  Dist::Zilla::Plugin::Test::ReportPrereqs: 0
  Dist::Zilla::Plugin::Test::UseAllModules: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Merged: 0
  MooseX::Declare: 0
  Pod::Weaver::Plugin::Encoding: 0
  Pod::Weaver::Plugin::WikiDoc: 0
  Test::CPAN::Meta: 0
  Test::UseAllModules: 0
  true: 0
resources:
  bugtracker: https://github.com/xdbr/dist-zilla-pluginbundle-author-dbr/issues
  homepage: https://github.com/xdbr/Dist-Zilla-PluginBundle-Author-DBR
  repository: https://github.com/xdbr/Dist-Zilla-PluginBundle-Author-DBR.git
version: 1.2.0
x_authority: cpan:DBR
